version: '3'
  
services:
  test:
    build:
      context: .
    healthcheck:
      # NOTE; || kill 1 stops the postgres process
      test: pg_isready -d postgres && pgrep -af 'walreceiver streaming' || kill 1
      interval: 20s
      retries: 2
      start_period: 20s
      timeout: 10s
    environment:
      # Required for the container to start, but will be removed after slave setup
      POSTGRES_PASSWORD: vaXXtzYi6F3UpcHCv
      REPLICATE_FROM_HOST: master
      POSTGRES_REPLICATION_USER: replication_ep_onsite
      POSTGRES_REPLICATION_SLOT: replication_slot_ep